POSTS = [
    {
        "store_name": "Rouiba Market",
        "product_name": "Bread Loaf",
        "title": "Fresh bread, baked this morning",
        "description": "Our white loaves come out of the oven before sunrise. Drop by while they're still warm.",
        "category": "Grocery",
    },
    {
        "store_name": "Rouiba Market",
        "product_name": "Olive Oil",
        "title": "Extra-virgin olive oil back in stock",
        "description": "Cold-pressed 750ml bottles, perfect for salads and finishing.",
        "category": "Grocery",
    },
    {
        "store_name": "Green Grocers",
        "product_name": "Organic Apples",
        "title": "New batch of organic apples",
        "description": "Crisp red apples from local growers. 1kg bags.",
        "category": "Produce",
    },
    {
        "store_name": "Green Grocers",
        "product_name": "Avocados",
        "title": "Hass avocados — perfectly ripe",
        "description": "Pack of 3, ready to eat today or tomorrow.",
        "category": "Produce",
    },
    {
        "store_name": "Tech Gadgets Hub",
        "product_name": "Wireless Earbuds",
        "title": "Bluetooth 5.0 earbuds — now in stock",
        "description": "Long battery life, low latency, comfortable fit.",
        "category": "Electronics",
    },
    {
        "store_name": "Tech Gadgets Hub",
        "product_name": "Smart Watch",
        "title": "Smart watch with fitness tracking",
        "description": "Heart rate, steps, sleep, and notifications on your wrist.",
        "category": "Electronics",
    },
    {
        "store_name": "Sara's Bakery",
        "product_name": "Croissant",
        "title": "Buttery croissants — fresh daily",
        "description": "Made with French butter, flaky and golden every morning.",
        "category": "Bakery",
    },
    {
        "store_name": "Sara's Bakery",
        "product_name": "Almond Cake",
        "title": "Almond and honey cake by the slice",
        "description": "Moist, fragrant, and just sweet enough.",
        "category": "Bakery",
    },
    {
        "store_name": "Fresh Catch Seafood",
        "product_name": "Sea Bass",
        "title": "Today's catch: whole sea bass",
        "description": "Gutted and scaled, ready for the grill or oven.",
        "category": "Seafood",
    },
    {
        "store_name": "Karim Electronics",
        "product_name": "Mechanical Keyboard",
        "title": "TKL mechanical keyboard, brown switches",
        "description": "Tactile, quiet enough for the office, satisfying for typing.",
        "category": "Electronics",
    },
    {
        "store_name": "Karim Electronics",
        "product_name": "Gaming Mouse",
        "title": "12000 DPI RGB gaming mouse",
        "description": "Lightweight, optical sensor, customisable lighting.",
        "category": "Electronics",
    },
]

REVIEWS = [
    {
        "post_title": "Fresh bread, baked this morning",
        "username": "gaceb_hicham",
        "stars": 5,
        "comment": "Best bread in Rouiba. Always fresh.",
    },
    {
        "post_title": "Fresh bread, baked this morning",
        "username": "benali_sara",
        "stars": 4,
        "comment": "Good crust, soft inside.",
    },
    {
        "post_title": "New batch of organic apples",
        "username": "meziane_karim",
        "stars": 5,
        "comment": "Crunchy and sweet, kids love them.",
    },
    {
        "post_title": "Bluetooth 5.0 earbuds — now in stock",
        "username": "abdellaoui_mohamed",
        "stars": 4,
        "comment": "Sound is great, fit could be better.",
    },
    {
        "post_title": "Smart watch with fitness tracking",
        "username": "abdellaoui_mohamed",
        "stars": 5,
        "comment": "Battery lasts a full week, very happy.",
    },
    {
        "post_title": "Buttery croissants — fresh daily",
        "username": "gaceb_hicham",
        "stars": 5,
        "comment": "Tastes like Paris.",
    },
    {
        "post_title": "Almond and honey cake by the slice",
        "username": "meziane_karim",
        "stars": 4,
        "comment": "Lovely flavour, a bit too sweet for me.",
    },
    {
        "post_title": "Today's catch: whole sea bass",
        "username": "benali_sara",
        "stars": 5,
        "comment": "Genuinely fresh, you can tell.",
    },
    {
        "post_title": "TKL mechanical keyboard, brown switches",
        "username": "benali_sara",
        "stars": 5,
        "comment": "Switches feel great, build quality is solid.",
    },
    {
        "post_title": "12000 DPI RGB gaming mouse",
        "username": "gaceb_hicham",
        "stars": 4,
        "comment": "Tracks well, RGB is a bit much but you can turn it off.",
    },
]
