# Generated by Django 6.0.3 on 2026-04-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField()),
                ('amount', models.IntegerField()),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card')], default='CARD', max_length=10)),
                ('entity_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('checkout_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired'), ('HELD', 'Held'), ('RELEASED', 'Released'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=10)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
