# Generated by Django 6.0.3 on 2026-04-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('HELD', 'Held'), ('RELEASED', 'Released'), ('REFUNDED', 'Refunded'), ('PAID_OUT', 'Paid Out')], default='PENDING', max_length=10),
        ),
    ]
