# Generated by Django 6.0.3 on 2026-04-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_product_image_product_is_blocked_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
