# Generated by Django 6.0.3 on 2026-04-26 01:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='chargily_id',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='store_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='id_document',
            field=models.ImageField(blank=True, null=True, upload_to='seller_docs/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='active_mode',
            field=models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller')], default='BUYER', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='user',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_wilaya', models.CharField(blank=True, max_length=100)),
                ('default_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('wilaya', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('chargily_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='users.sellerprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='DeliveryProfile',
        ),
    ]
